### ISSUE TITLE
32bits compilation fails

### ISSUE THREAD

**Issue by seb3773** [seb3773/showdeskten-kicker-applet#1]
"error: *** A compiler with support for C++11 language features is required" when trying to compile on Q4OS 32bits version.

**Comment by q4osteam** [comment]
Project compiles fine here on Q4OS-5 / 32bit. You may only need to install all the needed development packages:
q4os-devpack-base, tqt3-qtconfig, libtqtinterface-dev, tdelibs-trinity-dev, libtqt3-compat-headers

**Comment by seb3773** [comment]
You're right, an essential package was missing on my 32bits installation, my mistake. Now it compiles ok on 32bits version too :)
Next step will be to create .deb packages for each versions, as moving the libraries in the right folder doesn't seem to be the 'clean' way for installing. I will look at it (the autogen.sh script fails to generate .deb packages right now)
